### PR TITLE
Verify Datetime json bug fixes

### PR DESCRIPTION
**Pull request by andreasohlund**
Waiting for 6.0.4 and 5.2.21 to be able to get a green build

### CODE REVIEW

**Comment by andreasohlund** [comment]
cc @danielmarbach

**Comment by andreasohlund** [comment]
@danielmarbach tests are now green for 5.2.21 and 6.0.4. Will exclude the other versions to make this green

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers ready for review

**Comment by andreasohlund** [comment]
@SimonCropp I'll see if I can add the external json one (separate pull)

**Comment by danielmarbach** [comment]
👍 good stuff @andreasohlund

**Pull request merged**
